name: Weekly mailwizz synchronization

on:
  # schedule:
  #   - cron: '0 0 * * 1'
  push

jobs:
  Daily run
    runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2