name: Weekly mailwizz synchronization

on:
  schedule:
    - cron: '0 0 * * 4'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
            MAILWIZZ_API_URL: ${{ secrets.MAILWIZZ_API_URL }}
            MAILWIZZ_PUBLIC_KEY: ${{ secrets.MAILWIZZ_PUBLIC_KEY }}
            MAILWIZZ_PRIVATE_KEY: ${{ secrets.MAILWIZZ_PRIVATE_KEY }}
            MAILWIZZ_X_API_KEY: ${{ secrets.MAILWIZZ_X_API_KEY }}
            MAILWIZZ_BASE_URL: ${{ secrets.MAILWIZZ_BASE_URL }}
            RETOOL_API_INSERT_DATA: ${{ secrets.RETOOL_API_INSERT_DATA }}
            RETOOL_API_EMAIL: ${{ secrets.RETOOL_API_EMAIL }}
            workflowApiKey: ${{ secrets.workflowApiKey }}
        run: python src/main.py
